### ISSUE TITLE
Description needs to be truncated

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gateway-paypal-express-checkout#171]
https://wordpress.org/support/topic/blank-modal-window?replies=6

Field: L_PAYMENTREQUEST_0_DESC0

**Comment by gedex** [comment]
Looking at the support forum, the truncation warning is not related to blank window. I could reproduce the blank modal window even without truncation warning.

**Comment by dwainm** [comment]
Seems like an issue with the PayPal iFrame. Can't find anything we can change in the plugin to prevent this yet. 

This occurs only when a user has already been authenticated through PayPal and then aborts or visits the cart page again.

**Comment by dwainm** [comment]
This bug doesn't seem to be on our side.

I find that `window.open` works when a user is not logged, but when logged a new window is not created. This must be intended behaviour but I'm not quite sure what else is expected here.

The other issue that came up seems to be more common so I'll send out 1.1.3 today.

**Comment by tommyshellberg** [comment]
I still think the description needs to be truncated; otherwise, PayPal does it themselves and returns a warning:

```
[L_ERRORCODE0] => 11812
[L_SHORTMESSAGE0] => Invalid Data
[L_LONGMESSAGE0] => The value of Description parameter has been truncated.
[L_SEVERITYCODE0] => Warning

```
Before:
`[L_PAYMENTREQUEST_0_DESC0] => The yearly subscription price is $100. This includes all five book sessions, reflections, session guide, and discussion questions, moderated online forums, 90-minute video dialogue with the group, and the recording. It does not include the price of the books.`

Truncated:

` [L_DESC0] => The yearly subscription price is $100. This includes all five book sessions, reflections, session guide, and discussion questio`
