### ISSUE TITLE
Billing phone number not mandatory after 1.2.0 update

### ISSUE THREAD

**Issue by karlmt** [woocommerce/woocommerce-gateway-paypal-express-checkout#254]
V1.2.0 removes the mandatory requirement from the billing phone number.

**Comment by allendav** [comment]
Hey @karlmt - do you mean you expect:

1) the buyer to be prompted on the store's checkout page to supply their phone number before completing the purchase

or

2) this extension to get the buyer's phone number automatically from PayPal

**Comment by karlmt** [comment]
Hi @allendav 

Number 1. On installing V1.2.0 the mandatory mandatory requirement from the billing phone number on the Woo checkout page is disabled.

**Comment by allendav** [comment]
Hi @karlmt ! 

OK, so in the spirit of express checkout we are trying to make it so that, if the buyer initiates checkout using the "Check Out with PayPal" button on the cart page, that when they are returned from PayPal to the site that they ideally can just click the "Place Order" button and be done.

Making the billing phone number required can disrupt that, since not all buyers will supply a phone number to PayPal.

It would be possible to add a filter to filter the "required" back to true - what would you think of having that (e.g. in a custom.php on your site) - or do you think this warrants an option in settings? (We try to avoid adding too many options, to avoid overwhelming users, but if this is commonly needed, we might.)

Thoughts?

**Comment by karlmt** [comment]
Thanks @allendav,

I see your point however I would personally add the option into settings as this would provide a better experience for non technical users. I had tried using the custom function approach but this did not resolve the issue. 

I use Paypal with a number of other payment options and find that sometimes I need to chase people up who submit emails with typos. 

`add_filter( 'woocommerce_billing_fields', 'wc_filter_phone', 10, 1 );

function wc_filter_phone( $address_fields ) {
$address_fields['billing_phone']['required'] = true;
return $address_fields;
}`

Thanks again

Karl

**Comment by allendav** [comment]
I see your point - how about we add a checkbox to the settings as follows:

[ ] Require buyer to enter their telephone number during checkout if none is provided by PayPal

**Comment by karlmt** [comment]
Perfect!

**Comment by mikaey** [comment]
@karlmt -- On PayPal's end, there's a setting in the merchant's account to require a phone number from the buyer.  Do you have that setting turned on?  (It's not turned on by default -- so if you've never changed that setting, you might want to go into your PayPal account and turn it on.)

**Comment by karlmt** [comment]
Thanks @mikaey 

As I'm using a number of payment gateways this will not solve the issue for me. 

On another note, I'd be interested to know why the filter above is not working. 

Thanks again

**Comment by bor0** [comment]
This is partially fixed in d646806d. I will be adding the checkbox that the `required` status of the fields be dependent on.
