### ISSUE TITLE
Payment automatically goes to complete when payment action set to Authorize

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-paypal-express-checkout#260]
558730-zd-woothemes

#### What I expected

Payment should be on-hold and set to processing manually

#### What happened instead

Automatically goes through processing/complete

#### Steps to reproduce the issue

Payment action set to Authorize
![](https://cldup.com/yvn2xCDHA2.png)
Link to screenshot: https://cldup.com/yvn2xCDHA2.png

Make an order

Status automatically captures payment:

![](https://cldup.com/lRBHytBKUU.png)
Link to screenshot: https://cldup.com/lRBHytBKUU.png 

zd-ticket-577631

**Comment by mdmoore** [comment]
The delay before the the order is moved to processing is interesting.  I'm finding this happens instantly.  Also, the move to complete isn't happening for me, so that might be some type of auto-complete code at play.  

Stock is also being reduced twice.

![](http://cld.wthms.co/DmpUy+)
Link: http://cld.wthms.co/DmpUy.png

**Comment by yukikatayama** [comment]
Edit from my first post - even when status goes automatically through processing (when it shouldn't) it **doesn't** capture payment.

**Comment by yukikatayama** [comment]
Is there a possible timeline for this @allendav? thanks!

**Comment by mattyza** [comment]
@yukikatayama - I've assigned this to @bor0, along with a few others. We'll be working on a timeline for these over the next few days. Thanks for checking! :)

**Comment by bor0** [comment]
@yukikatayama / @mdmoore I keep getting `Sorry, we can’t complete your purchase at this time Please return to the merchant and choose another way to pay.` when I try to use "Authorize" payment action. However, it works file when it's "Sale". Any ideas?

**Comment by bor0** [comment]
@mdmoore can you please confirm that #269 fixes the double stock issue?

**Comment by mdmoore** [comment]
@bor0 The stock issue seems to be fixed in master.  Though, orders are still jumping to processing automatically.  

<img src="http://cld.wthms.co/UhG6Y2+" width="250"/>

`Sorry, we can’t complete your purchase at this time Please return to the merchant and choose another way to pay.` 

That's a pretty generic error.  Maybe double check credentials or try another sandbox account.

**Comment by yukikatayama** [comment]
Yes, I'm able to confirm it is jumping to processing as well:

![](https://cldup.com/w7cGwnQShh.png)
Link to screenshot: https://cldup.com/w7cGwnQShh.png

**Comment by bor0** [comment]
Do you have a test buyer account I can use for this ticket? Thanks!

**Comment by bor0** [comment]
@yukikatayama / @mdmoore can you please check if #272 resolves the issue? Thanks!

**Comment by yukikatayama** [comment]
@bor0 Ah, ok, @mdmoore and I tested on a live PayPal account and with the master and we were able to get the desired result of having the Authorized order stay on-hold. However, when we tried to complete/process the order, we noticed there is no transaction ID in the order or IPN notification in the notes:

![](https://cldup.com/jmRLUWn7gn.png)
Link to screenshot: https://cldup.com/jmRLUWn7gn.png

![](https://cldup.com/bBV3_H-bKS.png)
Link to screenshot: https://cldup.com/bBV3_H-bKS.png

**Comment by bor0** [comment]
This issue's description was fixed by PR #272. @yukikatayama / @mdmoore / @madeincosmos please file any potential additional tickets targeted for 1.4.0 and we'll start addressing them.
