### ISSUE TITLE
Transaction ID not viewable in order or order notes

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gateway-paypal-express-checkout#299]
Along the same lines of #289, the Transaction ID is not shown in the order notes and/or in the visible meta data. It is in the hidden meta data under `_transaction_id`. 

### Steps to reproduce

1. Purchase a product with gateway
1. View order in admin
1. Transaction ID not visible in order ❌ 

Reported in forum thread:
https://wordpress.org/support/topic/cant-see-transaction-id-in-order-notes/

**Comment by bor0** [comment]
@jessepearson the transaction ID is shown as follows:
![screen shot 2017-07-13 at 11 55 25 am](https://user-images.githubusercontent.com/1620929/28161031-4319e64a-67c2-11e7-9207-4b18d5ce0e5b.png)

Can you confirm you're seeing that?

**Comment by jessepearson** [comment]
@bor0 I can't believe I missed that. I believe that most people, including myself, are expecting a note in the order with this information, so it is being overlooked. Would this issue be able to be switched from being a bug to an enhancement so that can be added in the future?

**Comment by thenbrent** [comment]
Because WC core has a transaction ID API already, it's much better for this extension to work with that than add its own API.

For example, if adding the transaction ID to the orders notes is valuable with this gateway, then it would also be valuable with other gateways, in which case, it should be handled by WooCommerce core itself rather than a single payment gateway extension.

Because of that, I'm closing this. Feel free to request WooCommerce core add the note with the transaction ID if the current location is not sufficient.

**Comment by fouadbera** [comment]
i test with sandbox paypal and the transaction ID always shown empty any clarification on that please ?
