### ISSUE TITLE
Error 10412 when using PayPal Express

### ISSUE THREAD

**Issue by adeelejaz** [woocommerce/woocommerce-gateway-paypal-express-checkout#336]
When a customer returns back to our website to agree to terms and checkout (from the PayPal website), hitting the Submit button returns the following error:

PayPal error(10412): An error (10412) occurred while processing your PayPal payment. Please contact the store owner.

The order is created with a pending state but there is no record on the PayPal side. We have the latest version of Woocommerce and PayPal Express installed.

We tried placing an order ourselves and got the same error.

**Comment by adeelejaz** [comment]
Updating to WooCommerce 3.2.5 has fixed the issue.

**Comment by adeelejaz** [comment]
This is happening again now. Even with the latest version of Woocommerce and PayPal Express Checkout plugin

**Comment by raestanton** [comment]
I'm getting the same error message, how did you resolve please?

**Comment by adeelejaz** [comment]
@raestanton I found the issue to be duplicate invoice numbers that get sent to PayPal. There were already PayPal transactions with same invoice numbers so all I did was bump up the post id autoincrement to make sure we get completely new set of invoice numbers.

**Comment by mishtake23** [comment]
Bro can u please help me how to do that

**Comment by automattic-ian** [comment]
Reopening as that seems to be happening now in WooComerce 4.7

**Comment by jorgeatorres** [comment]
Hi everyone,

Error 10412, as pointed out above, is due to [duplicate invoice numbers](https://developer.paypal.com/docs/nvp-soap-api/errors/#10412). If you have various sites using PayPal Checkout or have gone through various re-installs of the same site, it is perfectly possible for invoice numbers to repeat (as these are generated from order IDs), which causes some issues on the PayPal side during checkout.

To help with this, PayPal Checkout includes an "Invoice Prefix" setting that can be used to make sure invoice numbers sent to PayPal are different (<Prefix><Order ID> is what gets sent). By default this prefix is set to "WC-" which means, it'll be shared among various WooCommerce sites tied to the same PayPal account unless the value has been set differently.
To change the prefix on a site, go to **WC > Settings > Payments > PayPal Checkout > Invoice Prefix** and save the changes.

Alternatively, incrementing the post ID in the `wp_posts` table can solve the issue, but if there are other sites using the same invoice prefix, invoice numbers can eventually collide again.

**Comment by webrafting** [comment]
confirmo, que solo cambiando el prefijo de los pedidos, se soluciona este problema.

i confirm that changing "Invoice Prefix" problem is solved
