### ISSUE TITLE
PPEC not showing when Subscriptions has a trial period

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-paypal-express-checkout#367]
Ticket: 892547-zd-woothemes
2453478-zen

Speaking with Prospress, I believe this is a bug, but want to double check this is not expected behavior.

Tested with PPEC 1.5, WC 3.2.6, and Subscriptions 2.2.16. 

**What was expected:**

With a subscription that either has a free trial or synchronized renewals (so initial transaction is $0), PPEC should show.

**What happened instead**

With a subscription that either has a free trial or synchronized renewals (so initial transaction is $0), PPEC _does not_ show. Does show, if there is a sign up fee, so it seems to be a behavior with having $0 transactions.

Question - My testing was done without Reference Transactions and in Sandbox mode. Does that play a part in this?

Steps to reproduce:

1. Create a subscription that has a free trial
2. Add to cart and in cart and checkout, notice that PPEC is not shown.
3. This happens with synchronized renewals enabled too
4. If you remove those to options or add a sign up fee, PPEC shows

**Comment by roykho** [comment]
From what I remember way back when, many gateways cannot/will not process zero dollar values. Also I believe WC will not load gateways when it is zero dollars I think.

**Comment by roykho** [comment]
Closing this for now. The work around is have at least a sign up fee of say $1.00 just so PP can process an amount.

**Comment by thenbrent** [comment]
> many gateways cannot/will not process zero dollar values

PayPal will allow a billing agreement to be created even if no amount is charged immediately to that amount. This is done in a separate request to processing the first payment (with the [`CreateBillingAgreement` request type](https://developer.paypal.com/docs/classic/api/merchant/CreateBillingAgreement_API_Operation_NVP/)).

> I believe WC will not load gateways when it is zero dollars I think

You are right, but Subscriptions overrides that so that and ensures gateways are loaded so that the gateway can do whatever it needs to do to set things up to process future automatic payments.

**Comment by roykho** [comment]
So perhaps this isn't a bug but an enhancement? Unless PPEC did support fee trials before?

**Comment by thenbrent** [comment]
@roykho PPEC didn't support _Subscriptions_ before. But once it started to support Subscriptions, it needed to support free trials because there is no way for a gateway to say it does or doesn't support free trials atm. It's a requirement of any gateway that [supports `subscriptions`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/41fc9263d4cb0b15cd4101446b414fffdc1c8588/includes/class-wc-gateway-ppec-with-paypal-addons.php#L15).

Handling $0 orders is also required to be able to support [_Customer Payment Method Changes_](https://docs.woocommerce.com/document/subscriptions/customers-view/#section-10), and [PPEC declares support for that feature](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/41fc9263d4cb0b15cd4101446b414fffdc1c8588/includes/class-wc-gateway-ppec-with-paypal-addons.php#L20). I'm not sure if that's working already (and the same code can be use for free trials), or if that's also broken along with free trials.

**Comment by hannahswain** [comment]
Another ticket where this is a problem: zd-1099376

**Comment by AashikP** [comment]
Another report in 1844903-zen

**Comment by rtddev** [comment]
@roykho - Is anyone going to be working on this issue?

**Comment by harishankerr** [comment]
We have another report of this in 2013871-zen. 

@roykho Based on my tests, Stripe shows up as the payment method for for $0 purchases of Subscription products. It appears that PayPal Checkout is not appearing though for products that have an initial price of $0, but have recurring payments involved. Would y'all have the bandwidth to take a look at this?

Thanks!

**Comment by rtddev** [comment]
@harishankerr - the immediate workaround (hack) for this is to setup a sign-up fee for $0.01

**Comment by chrisspiegl** [comment]
I have seen the exact same issue and recently opened (now closed) #592 . I also see Stripe working with $0.00 trial periods as well (and this is the more important forme) as with Synchronized Subscriptions (setting the payment date to the 1st of the next month for example so all subscriptions are charged on the same day).

I would love to see a solution that is not to have a signup-fee since a $0.01 signup fee is a) a deterrent for the person purchasing, and b) kinda strange with the fees (not sure how those are charged on such low transfers).

I hope there is something that can be done.

**Comment by tommyshellberg** [comment]
This has come up again in 2396264-zen. I actually see PayPal Checkout as a payment option when purchasing a Subscription with a free trial. However, I get errors in the console when trying to checkout.

```
Error: No value passed to payment
payment/this.memoizedToken<@https://www.paypalobjects.com/api/checkout.js:35484:21
dispatch@https://www.paypalobjects.com/api/checkout.js:1069:34
resolve@https://www.paypalobjects.com/api/checkout.js:991:10
ZalgoPromise/<@https://www.paypalobjects.com/api/checkout.js:945:19
dispatch@https://www.paypalobjects.com/api/checkout.js:1069:34
resolve@https://www.paypalobjects.com/api/checkout.js:991:10
chain/<@https://www.paypalobjects.com/api/checkout.js:1053:23
dispatch@https://www.paypalobjects.com/api/checkout.js:1069:34
resolve@https://www.paypalobjects.com/api/checkout.js:991:10
dispatch@https://www.paypalobjects.com/api/checkout.js:1108:17
resolve@https://www.paypalobjects.com/api/checkout.js:991:10
ZalgoPromise/<@https://www.paypalobjects.com/api/checkout.js:945:19
xhrLoad@https://www.paypalobjects.com/api/checkout.js:1821:14
```

![https://cld.wthms.co/a88iv4](https://cld.wthms.co/a88iv4+)
Image link: https://cld.wthms.co/a88iv4

**Comment by treibalen** [comment]
Another report on forums - https://wordpress.org/support/topic/gateway-not-available-on-subscription-with-free-trial/

I verified that I don't see PPEC during checkout if a subscription has free trial.

**Comment by conschneider** [comment]
I will take a look this later today.

**Comment by conschneider** [comment]
I did some research for this. I imagine we can make this work, but it will take some effort.  

- PayPal Checkout in general does not allow zero sum transactions like Roy pointed out correctly. 
- For creating recurring payments there is an argument list available to facilitate trial periods: https://www.paypal-community.com/t5/Holds-reversals-reserves/Trial-Payments-How-to-get-Amount-Zero-at-Checkout/td-p/787334 >> from what I see `TRIALBILLINGPERIOD` et al looks useful. However this does not fit in the current architecture and would take some extensive refactoring probably. 

I think if we leverage Reference Transactions we can make this work with `NVP` and zero sum orders. We maintain the method but change the billing agreement type for WooCommerce Subscriptions items. 

- We currently use `METHOD'  => 'CreateBillingAgreement'`. 

- Currently we pass : 
  `$params['L_BILLINGTYPE0'] = 'MerchantInitiatedBillingSingleAgreement';`

- I think we can adapt this for WooCommerce Subscriptions to: 

  `$params['L_BILLINGTYPE0'] = 'MerchantInitiatedBilling'; `

Example usage: https://www.paypal.com/gf/smarthelp/article/how-do-i-use-express-checkout-with-reference-transactions-ts1502 - note that the docs specifically mention that: 

![](https://cld.wthms.co/T8AbXm+)
Image Link: https://cld.wthms.co/T8AbXm

API Doc reference: https://developer.paypal.com/docs/classic/express-checkout/ec-set-up-reference-transactions/#set-up-the-payment-authorization

I did a quick test and with `$params['L_BILLINGTYPE0'] = 'MerchantInitiatedBilling'; ` I can checkout with a total amount of zero.  

This is not a quick and easy fix, but will take more time to integrate correctly for all processes (order creation, switching). 

But I think it can work like this.

**Comment by LZL0** [comment]
Why hasn't this been figured our and solved yet?

**Comment by lesloups-uk** [comment]
very good question, it seems crazy that it's still not supported?

**Comment by LZL0** [comment]
@lesloups-uk it has been already solved. See the latest version of the plugin.

**Comment by chrisspiegl** [comment]
I have updated, disabled, and enabled the plugin but so far I am not lucky to getting it to working with a subscription which is synchronized to the first of the following month.

I  assuming it has to do with this, that's why I am posting here. But if it is not, I also can open a new issue (and ideally, I would love to just get a hint for what I could change to fix this 🙈).

```
PayPal error (11452): An error (11452) occurred while processing your PayPal payment. Please contact the store owner for assistance.
```

Thanks and I hope we can figure it out.

**Comment by thenbrent** [comment]
@chrisspiegl that sounds like a different issue. Would you mind opening a new issue for it? This one has been closed and we don't want your issue to be lost. :)

**Comment by chrisspiegl** [comment]
Thank you @thenbrent. For now, I will not add a new issue because I found a statement on the [Paypal Support Page](https://www.paypal.com/gi/smarthelp/article/why-did-i-get-api-error-code-11452-ts2034) which suggests that the error is because I do not have the reference transactions active on the account. I will try that before opening any new issue here. But I have to say that I find it quite annoying on PayPals end to not activate this by default (and the support to be somewhat uneducated when requesting it :( maybe this time it goes better).
