### ISSUE TITLE
Logo Image not displaying in PayPal Checkout page

### ISSUE THREAD

**Issue by fhaps** [woocommerce/woocommerce-gateway-paypal-express-checkout#371]
**Tickets affected:**

909582-zd-woothemes

**Expected behavior:**

I expected the logo image setup in the plugin's settings to show up in PayPal's Checkout page.

**Actual Behavior**

Image doesn't display, only the "Brand Name" shows up.

**Steps to reproduce:**

1. Go to **WooCommerce > Settings > Checkout > PayPal Express Checkout** and upload an image measuring 190 x 90 pixels in the **Logo Image** field. Save changes.
2. Go to the front-end, add a product to cart and click on the PayPal Express Checkout button.
3. This will redirect you to the checkout page, where the image should appear, but it doesn't.

This is the logo image I uploaded in the settings:

![](http://cld.wthms.co/PuyAbk+)
Image Link: http://cld.wthms.co/PuyAbk

This is what the PayPal checkout page looks like:

![](http://cld.wthms.co/5Qyryz+)
Image Link: http://cld.wthms.co/5Qyryz

For comparison, when setting up a Logo image in the **PayPal Standard** settings, this is how it shows up. It's my understanding that this is where the Logo Image should also be displaying for **PayPal Express Checkout**.

![](http://cld.wthms.co/xHpLOd+)
Image Link: http://cld.wthms.co/xHpLOd

**Comment by formosattic** [comment]
In case this is relevant to the issue, the **Customizing Express Checkout - NVP/SOAP** method is now deprecated: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECCustomizing

**Comment by dechov** [comment]
It works for me with latest master (after https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/375) — however:

a) only in Live environment, not Sandbox

b) the size is scaled down to 150x150, due to the 'thumbnail' size being grabbed from the media library ([reference](https://codex.wordpress.org/Post_Thumbnails#Thumbnail_Sizes)). Besides making the logo appear a bit too small, it makes the header appear far too small (and be entirely obscured by the logo, in my case).

c) when clicking "Continue to payment" from the _checkout_ page, not cart ("PayPal Mark" must be enabled in settings). From the cart, I see only the contents of the rectangle in a pop-up, with none of the surrounding margin where the image would be. I suppose this is expected?
![screen shot 2018-01-26 at 2 59 00 pm](https://user-images.githubusercontent.com/1867547/35522728-170ab8ec-04eb-11e8-89c8-793a10f2aa52.png)

cc @bor0

**Comment by bor0** [comment]
> only in Live environment, not Sandbox

We send the same params for both live/sandbox, so I imagine this is a PP limitation.

**Comment by allendav** [comment]
Works in live, not sandbox. PayPal limitation. Nothing we can do. Closing.
