### ISSUE TITLE
Paypal forcing customers to register paypal account

### ISSUE THREAD

**Issue by vesceram** [woocommerce/woocommerce-gateway-paypal-express-checkout#379]
Hello
I have business paypal account and this plugin for payments and choose Landing Page: Billing (non-paypal account) but on checkoutnow paypal page customer must "Create your paypal account" to make payment just with credit card??

**Comment by formosattic** [comment]
This could be because the sandbox account created is missing some **Funding** details.

I managed to get mine working with a sandbox account created with this [guide](https://developer.paypal.com/docs/classic/express-checkout/ec_test_your_integration/) which is now deprecated, so follow this instead https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/test-express-checkout/

When checking the sandbox account created, it should show some info under the **Funding** tab.

On https://developer.paypal.com/developer/accounts/
<img width="866" alt="screen shot 2018-03-26 at 12 08 24" src="https://user-images.githubusercontent.com/15944096/37886679-65788a7e-30ef-11e8-8bf8-351cd720b4cf.png">

Sandbox profile:
<img width="752" alt="screen shot 2018-03-26 at 12 06 58" src="https://user-images.githubusercontent.com/15944096/37886688-6d8a6f66-30ef-11e8-9ab6-fd92357eebfb.png">

**Comment by leefogel** [comment]
@vesceram I'm having the same issue. Did you resolve this? If so, can you please share your solution?

**Comment by vesceram** [comment]
There is no solution if you are not from USA this option is not avaiable for you and me :(

**Comment by zwiesman31** [comment]
Also reported and tested in 2372861-zen

**Comment by thenbrent** [comment]
If your PayPal account is setup to have PayPal accounts be options, this extension will request PayPal provides your store's customers with the guest checkout option (this is on by default, and has been since version 1.1.3 by setting `SOLUTIONTYPE=Sole`).

To enable the PayPal account optional setting:

1.    Log in to your PayPal account.
1.    Click the **Settings** icon next to Log Out.
1.    Click **Website payments** under "Products & Services" on the left of the page.
1.    Click **Update** next to Website preferences.
1.    Click **On** for PayPal Account Optional.

(These steps may be different depending on your country or account type as PayPal.com changes their administration interface).

However, even with this setting enabled, and the PayPal Checkout extension requesting guest checkout be made available, **PayPal do not always make guest checkout available**.

From PayPal.com:

> Buyers don't always have the option to complete their purchases without using or creating a PayPal account. This option is presented based on several risk factors, including but not limited to the buyer's PayPal purchase history, PayPal cookies stored on the buyer's computer, the buyer's location, or a credit assessment.

Source: https://www.paypal.com/us/smarthelp/article/how-do-i-accept-credit-cards-with-express-checkout-using-the-guest-checkout-option-ts1623

Therefore, there is no guarantee that guest checkout will be made available to your customers when using PayPal Checkout, either via this extension or any other, because that decision is made by PayPal.

Because there is nothing that can be done to control guest checkout availability from the WooCommerce side, I will close this issue now.

To check if this feature is available in the country where your business or customers are located, please contact PayPal support.
