### ISSUE TITLE
Billing address is not required even if PayPal Express is disabled

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-paypal-express-checkout#386]
PayPal Express checkout has a feature where the Billing fields are set to non-required fields. This works great when this needs to be used for PayPal Express. However this is always turned on as soon as the plugin is active. Even if we disable the PayPal Express as a checkout option, it still modifies the billing fields.

Should we add an additional check there to make sure the checkout option is actually enabled?

**Comment by mensmaximus** [comment]
As you can see from the referenced issue setting the 'address_1', 'city', 'postcode' and 'country' to not required is a problem in some countries due to tax laws requiring the full address to be printed on an invoice.

Shops in Germany which do not use the paypal express feature (no express checkout at a single product or the cart) but use paypal as a standard payment gateway (at the woocommerce checkout site) need to collect a customers full address. 

As long as at least one product needs shipping everything works perfect. The fields in question are required. The problem arises if the cart contains only virtual products. Now customers can checkout without address.

But even shops located in other countries where the tax law requirements maybe be less strict might run into a problem. The plugin hooks into `woocommerce_default_address_fields` from the constructor in class `WC_Gateway_PPEC_Checkout_Handler` and modifies the fields regardless whether the paypal payment gateway is used (as mentioned by @mikkamp) and regardless which payment option a customer is using. 

Before I found this to be an issue with "WooCommerce PayPal Express Checkout Gateway" I tried to simply require the fields in question again using the filter `woocommerce_checkout_fields` to no avail. I guess this is due to the output buffering performed by the plugin.

Because class `WC_Gateway_PPEC_Checkout_Handler` does not use the singleton pattern it is not possible to remove the filter. As for now the only way to require those fields again seems to be to hook into `woocommerce_default_address_fields` later

```
add_filter( 'woocommerce_default_address_fields', 'mmx_require_default_fields', 50 );
function mmx_require_default_fields( $fields ){
	$fields['address_1']['required'] = true;
	$fields['city']['required'] = true;
	$fields['postcode']['required'] = true;
	$fields['country']['required'] = true;
	return $fields;
}
```

This will work for those shops described above (Germany, no express checkout, simple paypal payment gateway). I have not tested what will happen if such a store uses paypal express at the cart as well (should work but not tested).

This feature should be carefully reviewed. At least the whole plugin should not perform any actions if the gateway is disabled and there should be a checkbox to force required fields.

**Comment by NickGreen** [comment]
I'll add my voice to this issue. We've just had a support customer with all virtual products who, because this option is unchecked by default, was getting an error for all customer who were checking out without their shipping address.

This could've been avoided by checking that option by default on install.

**Comment by formosattic** [comment]
Hi @budzanowski, could you have a look at this? 

This is affecting subscriptions renewals (see 1004992-zen), and could have bigger impact.

Thanks!

**Comment by joelwills** [comment]
Pinging @budzanowski as per the above, thanks!
