### ISSUE TITLE
Button size: "medium" uses "small" dimensions

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#421]
When selecting the "medium" size for the PPEC buttons, the "small" size is used. 

![Size selections](http://cld.wthms.co/azJ4vy+)
Full size: http://cld.wthms.co/azJ4vy

When switching to "small" from "medium", the image size stays the same.

**Comment by dechov** [comment]
I couldn't reproduce a behavior in which actually selecting "Medium" resulted in a "Small" size button, or in which selecting either "Small" or "Medium" resulted in the same size button.

But thanks to this report, I've fixed a bug (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/409/commits/da36c838c77860a1cf9d49db0f04a242643a3c1c) in which "Medium" showed up after save, even when "Small" was selected. Is it possible that the issue was of this nature? And if not, would you mind outlining the steps that led to this behavior?

**Comment by hannahswain** [comment]
Yup, I think I got confused between the two different issues. This should now be sorted. Thanks!

**Comment by dechov** [comment]
Great 👍
