### ISSUE TITLE
Button layout: no change visible?

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#423]
Making changes to the global layout settings for `button layout` and `button size` don't affect the single product page buttons - while the `button color` and button shape` do affect the single product page. 

I'd expect that the global settings affect all of the buttons, including the single product page, _unless_ the options are set in the `Single product button settings`. Otherwise, make clear which options affect the single product page.

![Options](http://cld.wthms.co/UYK5Nn+)
Full size: http://cld.wthms.co/UYK5Nn

**Comment by dechov** [comment]
👍 Since there was no good reason not to have the choice use global settings for the single product page, I've now (in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/409/commits/d77d87e7dd835f65599ff872a3b210185318764a) given it the same optional treatment as the regular checkout settings, except that in this case the option to overwrite will be enabled by default (since a different layout is recommended):

<img width="670" alt="screen shot 2018-06-14 at 7 34 47 pm" src="https://user-images.githubusercontent.com/1867547/41443323-1d02340c-700a-11e8-98c8-f6ec41ba7f0b.png">

Let me know if there's still potential for confusion.
