### ISSUE TITLE
Address not being sent to PayPal 

### ISSUE THREAD

**Issue by pons1991** [woocommerce/woocommerce-gateway-paypal-express-checkout#448]
When I am trying to pay with PayPal and choosing guest checkout, PayPal is asking for Billing address and my card details. Asking card details is fine. But I am bit concerned about asking Billing address. 

I dont want it to ask billing address. Please do the needful.

**Comment by dechov** [comment]
I believe this is fixed by https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/476, which pre-fills the address form on the PayPal side with store checkout form values. This is included in the latest release.

Feel free to re-open and provide a bit more detail if this is still an issue – thank you!
