### ISSUE TITLE
Javascript no longer enqueued as part of wp_enqueue_scripts

### ISSUE THREAD

**Issue by jenkoian** [woocommerce/woocommerce-gateway-paypal-express-checkout#493]
Due to #491 the `wc-gateway-ppec-smart-payment-buttons` script no longer gets enqueued as part of the `wp_enqueue_scripts` hook, which means if theme developers are enqueuing JS that specifically depends on being later that this, it will no longer work if they're using `wp_enqueue_scripts` and instead they'll need to use a hook later in the process. This could come as a particular surprise to those not familiar with the hook lifecycle and that scripts could be loaded outside of `wp_enqueue_scripts`

That's a long way of saying this is a BC break and if following [semver](https://semver.org/) this should have gone in as a v2.x thing. Ideally though, you'd find a way to solve it whilst still enqueuing the JS in `wp_enqueue_scripts`.

**Comment by DanReyLop** [comment]
> That's a long way of saying this is a BC break and if following semver this should have gone in as a v2.x thing.

Sorry to hear that this change affected your theme. Even though we don't officially follow `semver`, we try to avoid breaking changes as much as possible. I've never even considered #491 to be a breaking change until now.

> which means if theme developers are enqueuing JS that specifically depends on being later that this, it will no longer work if they're using wp_enqueue_scripts and instead they'll need to use a hook later in the process.

Let's try to fix that! :)
Just to clarify. Is your problem that you rely on your theme's JS to run *after* the PayPal script? Or are you trying to enqueue some extra JS **only if** the PayPal JS was enqueued?
Maybe we can add some hooks or JS events depending on what your problem is. Relying on the order on which JS is loaded seems quite fragile.

> Ideally though, you'd find a way to solve it whilst still enqueuing the JS in `wp_enqueue_scripts`.

I tried but that's simply not possible. A theme's template can render a "mini cart" in any page, so the only point when we can know for sure that the JS is needed is when the HTML for the PayPal Buttons is actually rendered, and that happens much later than `wp_enqueue_scripts`.

> This could come as a particular surprise to those not familiar with the hook lifecycle and that scripts could be loaded outside of `wp_enqueue_scripts`

In this case we could implement it this way because the PayPal JS script is loaded in the footer, so it can still be enqueued while the page's body is rendering.

**Comment by jenkoian** [comment]
@DanReyLop thanks for your considered response! 😃 

I'll describe the issue we were facing and how we made it work and it may be that you have a better workaround anyway. 

So, we want to move the payment options (radio buttons) on checkout to the centre column, i.e. outside of the order review panel, but keep the button to pay in the order review panel. Which is all fine, however when we select paypal it ends up showing multiple paypal buttons in the right hand column. Note, this doesn't occur if we have the payment methods radio buttons as part of the order review, we haven't been able to work out why that is the case but suspect it's due to some javascript targeting a specific dom node or something.

Anyway, our 'hacky' way of making this work for us wast to write a custom bit of JS which looks something like this..

```javascript
$( document.body ).on( 'updated_cart_totals updated_checkout', function() {
	$('#woo_pp_ec_button_checkout > div').each(function( index ) {
		if ( index > 0 ) {
			$(this).remove();
		}
	});
} );
```

Which, although not ideal, did the trick. This needed to be loaded after `wc-gateway-ppec-smart-payment-buttons` though otherwise it wouldn't apply. We've fixed this now by hooking into `loop_end` which seems to kick in after the paypal stuff.

So yeah, that's our issue, we have a less than elegant workaround but it broke when we updated this plugin. We've fixed it by hooking into a later hook, but it caused us enough head scratching to motivate us opening this issue 😄 

Good point about the mini cart thing hadn't considered that.

**Comment by DanReyLop** [comment]
Ok, that's a tricky thing you're trying to do. It's kind of amazing that it works :)

So, a slightly simpler solution would be to change `$('#woo_pp_ec_button_checkout > div')` to `$('#woo_pp_ec_button_checkout')`. That would work regardless of the script order, and in fact, it would be better if your script runs before PayPal's. Now for the boring explanation:

The PayPal script uses the same events (`updated_cart_totals updated_checkout`) to render the button ([see here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/147f20958563fd3f937d3c06ff28b3cb28f0ade6/assets/js/wc-gateway-ppec-smart-payment-buttons.js#L150)). It so happens that because it's using `jQuery`, the buttons get rendered in **all** the elements with it `#woo_pp_ec_button_checkout` currently in the page.

When the review panel is refreshed using AJAX, an entire new one is returned from the server, including another `<div id="woo_pp_ec_button_checkout"></div>`. So the PayPal script will do its thing, render new PayPal buttons inside each one of these `<div>`s. In your solution, **after** the second set of buttons are rendered, you manually remove one of them (the buttons are rendered inside a `<div>` of the `#woo_pp_ec_button_checkout` element). **But**, if you remove the `#woo_pp_ec_button_checkout` element entirely *before* the re-render is triggered, then it won't be rendered in the first place. That should help prevent a bit of jankiness in the page too, specially on mobile or low-end hardware :)

I can't think of a more elegant solution without significant modifications in the extension's JS and/or PHP code, but considering that what you're trying to achieve is hacky (using JS to transplant a piece of a fragment that's also reloaded by AJAX), I think this is an acceptable compromise 😂

**Comment by jenkoian** [comment]
@DanReyLop thanks for the awesome response! 😃 I've quickly tried changing it to just remove `$('#woo_pp_ec_button_checkout')` within `wp_enqueue_scripts` but it seemed to remove all buttons. I'll try and find some time to proper debug it to see what order what is happening and report back.

**Comment by DanReyLop** [comment]
> but it seemed to remove all buttons.

You shoudln't remove *all* the `#woo_pp_ec_button_checkout`, what I suggested was to keep your code the same way, but instead of matching `#woo_pp_ec_button_checkout > div`, match `#woo_pp_ec_button_checkout`, like this:
```js
$( document.body ).on( 'updated_cart_totals updated_checkout', function() {
	$('#woo_pp_ec_button_checkout').each(function( index ) {
		if ( index > 0 ) {
			$(this).remove();
		}
	});
} );
```

I hope that works in your real code :)

**Comment by jenkoian** [comment]
@DanReyLop yeah I tried both, when I have more time I'll report back with more details.

**Comment by rohittm** [comment]
@DanReyLop I was able to observe the same. After the 1.6.5 update, the buttons from mini-carts didn't show up. I tested the same on Storefront and It used to show up till version 1.6.4:

![](https://cld.wthms.co/Le5Lsk+)
Link to the image: https://cld.wthms.co/Le5Lsk

And after 1.6.5 update:

![](http://cld.wthms.co/ZugYHT+)
Link to the image: http://cld.wthms.co/ZugYHT

I believe this is because of #491.

Affected ticket - 1697644-zd.
