### ISSUE TITLE
Check for minimum order amount bypassed until payment confirmation

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#505]
Using PayPal Express Checkout, it's not possible to have a check on the mimimum order amount before the final order confirmation.

## Steps to replicate

1. Use a snippet or plugin to set the minimum order amount, e.g. https://docs.woocommerce.com/document/minimum-order-amount/
2. Go to a product on the site that has a price lower than the minimum order amount 
3. Pay with PayPal directly on the product page, going through authentication 
4. Note the minimum order check on the final confirmation page

![Minimum order amount check on order confirmation](http://cld.wthms.co/EY7Fx0+)
Full size: http://cld.wthms.co/EY7Fx0

Given how likely a customer is to give up at this point, is there any way the PayPal Express Checkout plugin could merge more with the normal checkout flow that does allow for that kind of check?

Original source: https://wordpress.org/support/topic/possible-to-use-with-minimum-order-amt-function

**Comment by menakas** [comment]
@hannahswain 

When Smart Payment buttons are used on the single product page, all the checks that are usually put on the cart can be bypassed because the button is clicked on without the product being added to the cart.

One option is to disable the Smart buttons on single product page when the store wants to enforce minimum order amounts.

The other option is to use the `woocommerce_paypal_express_checkout_hide_button_on_product_page` filter to the hide the Smart Payment buttons on the product page if the price of the product is less than the minimum.

Do you think this would help?

**Comment by james-allan** [comment]
I agree with @menakas assessment here. Because the payment buttons bypass the cart, any validation, including custom validation like you linked, is bypassed until the final checkout step. 

While this is not an ideal UX, it's not something we can really fix because the validation requires a cart object and at the point of viewing the product page, a cart doesn't exist. 

If a particular store has validation like a minimum purchase amount, they can use the filter mentioned by Menaka. Outside of that, there isn't a way for us to provide the context required to call all validation until that final step. We might revisit this at some point in the future, but it's not a priority for us right now.

**Comment by hannahswain** [comment]
Thanks! I'll follow up on the forum thread.
