### ISSUE TITLE
Changing payment method to PayPal checkout for existing subscriptions does not prompt login

### ISSUE THREAD

**Issue by chaushevic** [woocommerce/woocommerce-gateway-paypal-express-checkout#518]
I am not sure whether this is a bug or intended behavior, could not find any reference to such an issue, maybe I am also missing something simple.

When changing payment methods for subscriptions to PayPal Checkout it does not prompt the user to log in with their PayPal account, but it still switched to PayPal Checkout as the new payment method. The standard PayPal gateway that ships with WooCommerce correctly redirects the user to PayPal to log in.

Steps to reproduce:
1. Have WooCommerce subscriptions active and an active subscription
2. Open the subscription (ex. /my-account/view-subscription/16/)
3. Go to Change Payment
4. Select PayPal Checkout as the method and click on 'Change Payment Method'
5. It saves PayPal Checkout as the new payment method even though it did not ask the user to log in with their PayPal account

**Comment by RadoslavGeorgiev** [comment]
Hi @thatwasnotme!

I checked how things work and the short answer is that WooCommerce Subscriptions has some specific hooks and filters that let it integrate with the built-in PayPal payment gateway.

As far as I can see, there is no such integration for Express Checkout at the moment. I will get in touch with WooCommerce Subscriptions' creators in order to define and scope the work that would be needed in order to do that, but the process will probably take a while.

**Comment by thatwasnotme** [comment]
Thanks @RadoslavGeorgiev

**Comment by mattallan** [comment]
Fixed with https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/640
