### ISSUE TITLE
Your PayPal checkout session has expired. Please check out again.

### ISSUE THREAD

**Issue by simduchaine** [woocommerce/woocommerce-gateway-paypal-express-checkout#532]
Every time someone is using the Paypal option on the checkout page, after the transaction once the browser returns back to our website, an error message is showing: ”Your PayPal checkout session has expired. Please check out again.”

I’ve tried clearing both server cache and browser cache, and changing browser, using multiple user accounts (both woocommerce account and PayPal accounts), the problem persists.

**Comment by v18** [comment]
Hi @simduchaine, I recommend reaching out directly to our support so they can assist you better here:

https://woocommerce.com/my-account/create-a-ticket/

As a first step to figure out the issue, you can try this on a staging site to see if the error still happens: deactivate all other plugins (keeping WooCommerce and PayPal Checkout) and use the default Storefront theme. If the problem doesn't happen under this condition, please try the theme on your live site to see if the problem returns. If not, try turning on your plugins one by one to see when the problem comes back.

Going to close this issue for now, please re-open if you are unable to reach support.
