### ISSUE TITLE
Enable PayPal Mark on checkout page by default

### ISSUE THREAD

**Issue by johndcoy-zz** [woocommerce/woocommerce-gateway-paypal-express-checkout#544]
With PayPal Checkout being the only payment gateway enabled for new sites, most users expect the payment method to show on the checkout page.

Can we enable PayPal Mark by default even though the purpose of this wasn't to be intended to be used as so?

Here are some requests for this in the forum alone for this: [#](https://wordpress.org/support/topic/how-to-add-a-yellow-paypal-button-on-checkout-page/), [#](https://wordpress.org/support/topic/place-order-button-missing-with-paypal-radio-button-selected/), [#](https://wordpress.org/support/topic/problem-245/)

**Comment by allendav** [comment]
> With PayPal Checkout being the only payment gateway enabled for new sites

Are you thinking PayPal Standard included with WooCommerce core, or are you sure you mean this extension, PayPal (Express) Checkout

**Comment by james-allan** [comment]
The PayPal mark for checkout is enabled by default.

<img width="581" alt="Screen Shot 2020-06-10 at 10 46 43 am" src="https://user-images.githubusercontent.com/8490476/84214781-b3ed1000-ab07-11ea-9295-430c0326d034.png">

Looking at the links including in the OP. The first one is asking about getting the PayPal **yellow buttons** to to appear on the checkout. Essentially they are asking for the smart payment buttons rather than the standard checkout flow that redirects to PayPal. Using SPBs is the default as of now. 

The second and third links are what appear to be a bug report, misconfigured settings or conflict. One says that the buttons appear and then disappear, this is most likely a bug rather than the default setting. In the situation outlined in the third link, I suspect they had misconfigured settings or a conflict which prevented the checkout from showing PayPal. 

With that in mind, I'm closing this issue. Feel free to reopen if I've missed something 🙂
