### ISSUE TITLE
Should Reference Transaction renewals use original Order's currency rather than Store Currency?

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce-gateway-paypal-express-checkout#607]
For renewals (using reference transactions), the gateway uses the current Store currency rather than the currency used for the initial order: 

`		$params['PAYMENTREQUEST_0_CURRENCYCODE'] = get_woocommerce_currency();`

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-client.php#L290

There are cases where these are not the same (for example, if the initial order was placed using a currency switcher plugin). Should the renewal user the original order's currency, instead?

**Comment by davidtzvi** [comment]
I'd just like to chime in, as I reported this issue via WooCommerce support. 

We have many recurring subscription renewals in our store that are in a currency different than our store's base currency. However, upon renewal, they are being charged the converted price, but in the store's base currency. 

For a concrete example of a problematic order, I can confirm that the order object has the order's currency set to USD. But, the WooCommerce log for PayPal Checkout, shows [CURRENCYCODE] => CAD for the renewal.

Which seems to be set here: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-client.php#L1005

I don't know if it's intentional behavior, or a limitation/bug, but in our case, it's quite problematic.

Thank you for reviewing this question/issue.

**Comment by mikkamp** [comment]
As mentioned, the currency is passed for reference transactions in the following code: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.6.17/includes/class-wc-gateway-ppec-client.php#L1005

I'd suggest to use the same code to get the currency from the order, as was recently added in a different location here: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/531/commits/6df306b48da83b8e754fb848d1d32fe0c8e48cba

**Comment by davidtzvi** [comment]
Thanks so much. I appreciate that this issue will be resolved.

It doesn't seem to be affecting our set up, but maybe also have a look at lines 290 and 884 as they are also using the store's base currency instead of the order currency.

**Comment by jessLundie** [comment]
Another report of this in 2476144-zen. Currency is being correctly stored in the DB, but renewal orders are being processed using store base currency.

**Comment by allendav** [comment]
@jessLundie @mikkamp - tagging this as Many: L - seems like we have three tickets/pings now
