### ISSUE TITLE
SameSite: A cookie associated with a cross-site resource at (X) was set without the `SameSite` attribute

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-paypal-express-checkout#642]
Multiple warnings appear in the developer console, but I still seem to be able to checkout using a sandbox PayPal account.

Tested with these flags set in Chrome under chrome://flags
#same-site-by-default-cookies: Enabled
#cookies-without-same-site-must-be-secure: Enabled

These will become the default in Chrome 80 (set to release around Feb. 21-28, 2020)(https://www.chromestatus.com/feature/5088147346030592) 

Add an item to your cart with this extension active. While on the cart page the SameSite warning is thrown for multiple resources:

http://stats.paypal.com/
https://paypal.com/
https://c.paypal.com/
http://paypal.com/
http://www.paypal.com/
http://www.sandbox.paypal.com/

When proceeding to checkout, the following also occur, in addition to many of those above

http://paypalobjects.com/

**Comment by codestor4** [comment]
#### Chrome ❌
I could not reproduce this on `Chrome 83.0.4103.97 (Official Build) (64-bit)`. I could not see any warnings related to PPEC or Woo in the developer console in Chrome during the checkout process. 

I enabled these flags:

```
#same-site-by-default-cookies: Enabled
#cookies-without-same-site-must-be-secure: Enabled
```

I added an item to the cart, purchased it via the Paypal Checkout button, and then placed an order. No warnings.

#### Firefox ❌
I tried this in `Firefox 77.0.1 (64-bit)` and found these warnings: 

```
Cookie “woocommerce_items_in_cart” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite woo1.local

Cookie “woocommerce_cart_hash” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite woo1.local
```

But those I believe are coming from WooCommerce Core and not PPEC extension.

cc: @jorgeatorres since this is currently assigned to you, were you able to repro this? :)

**Comment by jorgeatorres** [comment]
@codestor4: Those last warnings do seem to come from WC and not PPEC. I'm still not sure if there's something we can do to prevent those warnings at all.
That said, I was able to replicate the warnings from the original report both locally and under jsfiddle, and regardless of the configured "same-site" flags:

<img width="1520" alt="Screen Shot 2020-06-17 at 21 50 28" src="https://user-images.githubusercontent.com/184724/84965403-36b43300-b0e5-11ea-8cdc-9b0a8e81fa7a.png">

This is on Chrome  83.0.4103.106. Maybe there's something different in your environment (or in mine) 🤷🏻‍♂️.

**Comment by jorgeatorres** [comment]
I did some more testing and research on this. According to [this document](https://www.chromium.org/updates/same-site), Chrome is already enforcing this new cookie behavior for some users, but starting July 14th it'll be enforced for everyone on Chrome 80+.

I tested the checkout flow on several browsers (Chrome, Safari, Firefox) and even with the flags to block these cookies enabled, payments are possible and the experience behaves as expected.
From looking at the DevTools > Application > Cookies table, most of the blocked cookies are related to what seems to be some "logging" functionality on PayPal's side, and/or some kind of Google Analytics instance they're using.

Since these aren't cookies we're in charge of, I don't think there's anything we can do except keep an eye open for possible problems in the future, though that doesn't seem likely to happen. According to [a comment in the PayPal Checkout Components repo](https://github.com/paypal/paypal-checkout-components/issues/1230#issuecomment-618602310), they (PayPal) are already working on updating the cookies for the new policy and, in any case, "there should be no impact" despite the console warnings:

> The cookies are being steadily overwritten with the new samesite flag. For existing cookies you will continue to see these warnings, but there should be no impact. If you see any actual issues called, please raise a new github ticket with details. Thanks!

- - -

I'm going to close for now, but feel free to re-open the issue if I missed something or have misrepresented the information.
