### ISSUE TITLE
Unchecking Require Billing Address and Require Phone Number not working

### ISSUE THREAD

**Issue by straumer** [woocommerce/woocommerce-gateway-paypal-express-checkout#726]
### Describe the bug
On the checkout page, I get:
```
Billing Street address is a required field.
Billing Postcode / ZIP is a required field.
Billing Town / City is a required field.
Billing Phone is a required field.
```
Even though the **Require Billing Address** and **Require Phone Number** options in the settings are unchecked. If I unrequire the fields with the coding method [here](https://woocommerce.com/posts/customize-checkout-fields-woocommerce/), the field labels still show up with a star as if they're required and with no "(optional)" beside it, but I can still leave them empty and go on to the paypal page without errors.

This worked for me before, but I just updated my plugins along with this one since my last update in early March I believe.

### To reproduce
1. Uncheck and save **Require Billing Address** and **Require Phone Number** settings.
2. Go to checkout page and leave those fields empty and click the paypal button.
3. The errors mentioned above should show.

### Expected behavior
**Require Billing Address** and **Require Phone Number** unchecked should make the fields not required and they should show up as such (as optional).

**Environment (please complete the following information):**
 - WordPress Version: 5.4.1
 - WooCommerce Version: 4.1.0
 - PayPal (Express) Checkout Plugin Version: 1.6.21
 - Browser [e.g. chrome, safari] and Version: Firefox 75.0
 - Other plugins installed:
Contact Form 7
Google Fonts Typography
Newsletter
Nomiddleman Bitcoin and Crypto Payments for WooCommerce
OMGF
Simple Lightbox
Sticky Side Buttons
WooCommerce
WooCommerce Admin
WooCommerce Services
WooCommerce Side Cart
WP Mail SMTP

**Comment by mattallan** [comment]
Hi @straumer thanks for the report.

Your expected behaviour was actually a bug in PPEC and was fixed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/697

The **Require Billing Address** and **Require Phone Number** settings were originally only supposed to make the billing fields optional on the "Confirm your PayPal Order" page and not on the checkout.

See https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/426 for the issue.

If you would like to make all billing fields optional on the checkout, I would suggest hooking onto the `woocommerce_default_address_fields` filter and setting the 'required' value to `false` (see [this doc](https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/) for more details)

Closing this. Feel free to re-open if I've misunderstood your issue
