### ISSUE TITLE
Credit Card Payment for Canada always defaults to US

### ISSUE THREAD

**Issue by dcrowe1950** [woocommerce/woocommerce-gateway-paypal-express-checkout#733]
When a customer clicks on the credit card icon and the form is shown, the default location is always US. The store is in Canada and the customer is in Canada. 

Under Settings -> General the Site Language is set to English Canada.
I've checked with PayPal and have confirmed that all PayPal settings for the Store's Pay Pal account are correct for Canada.

This has been an ongoing issue since the introduction of the Smart Payment Button

**Comment by james-allan** [comment]
Hi @dcrowe1950 

Thanks for submitting this issue. 

I believe the issue here is that when the store is located in Canada we pass the locale code `en_US`. This is because according to [PayPal's docs](https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes), this is the English locale code to use. 

<img width="598" alt="Screen Shot 2020-05-22 at 11 13 28 am" src="https://user-images.githubusercontent.com/8490476/82621029-47c07000-9c1d-11ea-9e82-dc8606c19c15.png">

After some testing, it appears the PayPal docs are incorrect. Passing `en_CA` as the locale code appears to work as expected. I'll submit a patch to get that fixed up.
