### ISSUE TITLE
Cannot Remove PayPal Credit/Debit Option from Cart Page

### ISSUE THREAD

**Issue by skunkins** [woocommerce/woocommerce-gateway-paypal-express-checkout#744]
### To reproduce

1. Update to 2.0.1

**Screenshots**

https://prnt.sc/so2xih

### Expected behavior

I'd like to only have two options on my Cart Page, "Proceed to Checkout" and "PayPal."  After updating, it added PayPal's Credit/Debit Card option on my cart page.  If PayPal's credit/debit card option is there, users are more likely to click that rather than proceed to checkout.  My site will autofill for anyone that is logged in of they proceed to checkout.  How can I remove this button?  If I was to push this update to my live site, I would have to remove the option for customers to use PayPal on my cart page and I don't want to do that.

Any button that has an option to hide payments, I've removed every single payment option except Venmo and this is still happening. 

**Environment (please complete the following information):**
 - WordPress Version: 5.4.1
 - WooCommerce Version: 4.1.1
 - PayPal (Express) Checkout Plugin Version: 2.0.1
 - Browser [e.g. chrome, safari] and Version: All / most recent updates
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by jorgeatorres** [comment]
Hi @skunkins,

Thanks for reaching out!

> How can I remove this button?

You should be able to hide specific payment options by going to the gateway settings (WooCommerce > Settings > Payments > PayPal Checkout - Manage) and adding the methods you don't want displayed to the "Hide Funding Method(s)" list.
In your case, you should add "Credit or debit cards":

<img width="704" alt="Screen Shot 2020-05-26 at 10 20 35" src="https://user-images.githubusercontent.com/184724/82905712-92eac380-9f3a-11ea-9336-c8a7257c275d.png">

Your actual settings might be a bit different, depending on whether you have cart and/or checkout specific configuration enabled, but in all cases there should be a "Hide Funding Method(s)" list. Can you give this a try and let us know if it works?

**Comment by jorgeatorres** [comment]
@skunkins:

I initially missed this bit in your initial report (sorry):

> Any button that has an option to hide payments, I've removed every single payment option except Venmo and this is still happening.

So it seems you're already hiding the methods as per my comment above. If that's the case we would need more information in order to debug this further.

- Can you try clearing your browser's cache? If you're using caching plugins in your WP instance, can you give that a try also?
- Could you share a screenshot of your gateway settings?
- If you're able, can you use the Dev Tools (in Chrome, for instance) and see what the output of the following Javascript code is?
   ```wc_ppec_context.disallowed_methods```

I apologize if these steps seem trivial, but I've been trying to reproduce the problem locally and haven't been able to do it, which probably means there's something different in your settings or setup.

**Comment by skunkins** [comment]
Here's some settings, if you need more, let me know.  I just need to blank out personal information/API info.  

I tried clearing my cache and turning off any caching plug-ins (Autoptimize / Async JavaScript), that didn't fix it.  

Settings:
https://prnt.sc/so4nwv
https://prnt.sc/so4no1
https://prnt.sc/so4n6h

wc_ppec_context.disallowed_methods:
https://prnt.sc/so4xqs

**Comment by jorgeatorres** [comment]
@skunkins:

Thanks for getting back to us. We don't have "Cart" specific settings so the settings that are applying to your cart page are the "default" ones.
The `wc_ppec_context.disallowed_methods` output indicates that the exceptions you've added are not applying to the cart (which makes sense as Checkout/Mini-Cart is not the same as Cart) and that's because you're using the "Horizontal" layout for your button, which doesn't allow customizing the methods displayed. The final selection displayed to users is made by PayPal automatically and depends on a bunch of factors, including device type and location.

You should be able to fix this by switching the layout for your button to "Vertical", which enables the "Hide Funding Method(s)" setting. Adding "Credit or debit cards" [as explained above](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/744#issuecomment-634022443) should take care of the problem.

If you want for this same set of settings to apply to the Checkout page and or/ the mini-cart feel free to disable the "Configure settings specific to …" toggles and reduce the number of settings you need to keep an eye on.

Please give this a try let us know if it works!

**Comment by skunkins** [comment]
The reason I have it on horizontal is because if I switch them to vertical, the option to remove funding methods goes away, shown [here](https://prnt.sc/so6dr8).  

After switching to vertical, my checkout page now has the debit/credit card option which was hidden before, shown [here](https://prnt.sc/so6edk).

**Comment by jorgeatorres** [comment]
Hi @skunkins:

Thanks for the reply. Sorry if I wasn't clear before but I didn't suggest you switched to "Horizontal" but to "Vertical". That said, switching to "Vertical" shouldn't hide the funding methods option. Switching to "Horizontal" does, which is what your screenshot shows and what I think is the layout setting in use on your cart page.

Your screenshot shows that you're modifying the "Regular Checkout Button Settings", but those don't apply to the cart page: in order to remove the credit card option from the cart page you should be looking at the settings directly under the "Button Settings" header and **not** the "Regular Checkout Button Settings".

To summarize: this is how your "Button Settings" section should look like:

![](https://user-images.githubusercontent.com/184724/82905712-92eac380-9f3a-11ea-9336-c8a7257c275d.png)

Once again, it is important that you enable the "Vertical" layout and add the "Credit or debit cards" option to the "Hid Funding Method(s)" list. Make sure these changes are being made under the "Button Settings" section and not the other sections (_Mini-cart Button Settings_, _Single Product Button Settings_ or _Regular Checkout Button Settings_) as those don't apply to the cart.

If that still doesn't solve your problem, I think we might need to take a look at your test site, if that's possible.

**Comment by skunkins** [comment]
Very sorry, you indeed are correct.  I removed the independent customizations.  I wish it didn't load on the mini cart because that script loads on every page of the site and it hurts the site speed score.   

Thank you.

**Comment by jorgeatorres** [comment]
No problem. I understand all these settings can be confusing 😸 .

As for disabling the PayPal buttons on the mini-cart, I'm going to open an issue so that we can look into adding this feature in a future release.

**Comment by ozmensemih** [comment]
Hello I just want to remove the yellow button, is that `possible?

**Comment by ramosslyz** [comment]
is there a way to hide Title+Description in the Paypal invoice like picture down below ?
![Description_paypal_invoice](https://user-images.githubusercontent.com/92731157/202822489-0181c550-992c-4056-8fdc-1bef12e606c3.PNG)

**Comment by aficiomaquinas** [comment]
I wasn't able to fix the issue with @jorgeatorres fix. Ugly and hacky, but I just put this in my theme's css:

```
/* Hide PayPal Credit Debit Card Express Checkout Button */
#express-payment-method-ppcp-gateway-card {
	display: none;
}
```
