### ISSUE TITLE
"Debit or Credit Card" button gives error

### ISSUE THREAD

**Issue by slash1andy** [woocommerce/woocommerce-gateway-paypal-express-checkout#751]
### Describe the bug

in 2.0.1, trying to checkout with the "Debit or Credit Card" button gives an error about "something went wrong"

### To reproduce

1. Go to a product that has Smart buttons
2. Hit "Debit or Credit Card", proceed to checkout. I used the test number 4111111111111111
3. See error

**Screenshots**
![screenshot](https://i.ibb.co/wNkxCth/1.jpg+) **Image Link:** https://i.ibb.co/wNkxCth/1.jpg

### Expected behavior

Checkout to go through.

**Environment (please complete the following information):**
 - PayPal (Express) Checkout Plugin Version 2.0.1
 - Firefox 76 and latest Chrome
- Base storefront testing site
-  https://wootest2019.mystagingwebsite.com/product/100-cotton-gloves-with-velcro/

**Comment by mattallan** [comment]
Hi @slash1andy,

Thanks for opening an issue.

Sadly you cannot use the common test cards like `4111 1111 1111 1111` when filling out this new `Debit or Credit Card` payment form.

In order to test this card form you will need to create a test customer with a test card. Here are the steps to do this:
1. Log in to your PayPal developer account at https://developer.paypal.com/
1. On the left sidebar, click on Sandbox > Accounts
1. Create a Personal test account: https://d.pr/i/p34Qvf
1. Once that account has been created, view/edit the account and visit the funding tab: https://d.pr/i/QhNnXC
1. Use these account and card details to fill in this form.

**Comment by slash1andy** [comment]
This was also marked as resolved by 2.0.2 by the reporter in a forums thread (unsure if they were in sandbox) https://wordpress.org/support/topic/paypal-ver-2-0-1-credit-debit-not-working/#post-12901736
